version: '3.1'
services:
  odoo:
    image: odoo:16.0
    env_file: .env
    depends_on:
      - pgql
    ports:
      - "8069:8069"
    volumes:
      - data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom-addons:/mnt/extra-addons
  
  pgql:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - db:/var/lib/pgsql/data/pgdata

volumes:
  data:
  db: